weights: ./models/st_gcn.ntu-xview.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/NTU-RGB-D/xview/true_val_data.npy
  label_path: ./data/NTU-RGB-D/xview/true_val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: adversarial_attack
xs_or_xv: xsub
device: 0
test_batch_size: 1
iteration: 50
adversarial_op: pgd
constraint: L_inf
step_size: 0.01
threshold: 0.1
